export type Project = {
  slug: string
  number: string
  title: string
  type: string
  description: string
  tags: string[]
  color: 'coral' | 'blue' | 'yellow'
  role: string
  goal: string
  learned: string
  next: string
  demo: string
  source: string
  image?: string
}

export const projects: Project[] = [
  {
    slug: 'funmandarin',
    number: '01',
    title: 'Fun Mandarin',
    type: 'Mandarin Learning Management System · 2026',
    description: 'A Mandarin learning platform where students practice by HSK level, and teachers and admins run classes, assignments, and level-ups in one place.',
    tags: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Supabase'],
    color: 'coral',
    role: 'Product designer & developer',
    goal: 'Give Fun Mandarin one system for class enrollment, chapter practice, and teacher oversight instead of tracking lessons outside the product.',
    learned: 'Client work means turning a real teaching workflow into one product. The hard part was the rules: who can join a class, what unlocks next, and who can approve a level-up.',
    next: 'I would tighten role checks for students, teachers, and admins, and make empty states and the HSK promotion flow easier to understand.',
    demo: 'https://www.funmandarin.id',
    source: 'https://github.com/dunkindonut123/final_ver_fun',
    image: '/projects/fun-mandarin.jpg',
  },
  {
    slug: 'the-beauty-tailor',
    number: '02',
    title: 'The Beauty Tailor',
    type: 'Tailor studio site · 2026',
    description: 'A site for a Jakarta bespoke tailor, from the atelier’s story and cloth mills to booking a consultation.',
    tags: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    color: 'blue',
    role: 'Project eveloper',
    goal: 'Give The Beauty Tailor one place to present the atelier, the mills, and the services, and let someone book a consultation without calling the shop first.',
    learned: 'A service site has to sell the craft before the booking form. Visitors needed the atelier story, mills, and services in Indonesian before WhatsApp or email made sense.',
    next: 'I would make the consultation form clearer about what happens after submit, and add a simpler mobile path to book.',
    demo: 'https://thebeautytailor.id',
    source: 'https://github.com/dunkindonut123/tailor-shop',
    image: '/projects/the-beauty-tailor.jpg',
  },
  {
    slug: 'lost-and-found',
    number: '03',
    title: 'Lost & Found',
    type: 'Campus web app · 2026',
    description: 'A campus lost-and-found app for reporting found items, searching public listings, and claiming belongings through an admin review.',
    tags: ['React', 'Next.js', 'Supabase'],
    color: 'coral',
    role: 'Full-stack developer',
    goal: 'Give students one place to report found items and claim what they lost.',
    learned: 'Public listings and claims only work if the database enforces them. Row-level security and claim status checks had to block invalid claims, not just the form UI.',
    next: 'placeholder',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/lost_and_found',
    image: '/projects/lost-and-found.jpg',
  },
  {
    slug: 'fer-stress-detection',
    number: '04',
    title: 'FER Stress Detection',
    type: 'Machine learning · 2026',
    description: 'A face model that reads four emotions and marks fear and sadness as stress.',
    tags: ['PyTorch', 'EfficientNet', 'Computer vision'],
    color: 'yellow',
    role: 'Machine learning developer',
    goal: 'Tell stress-related expressions (fear, sadness) apart from happiness and neutrality on a single photo.',
    learned: 'How much time it takes to train an AI model and how images flow through the pipelines to eventually get trained on.',
    next: 'Experimented more with augmentation and preprocessing to increase accuracy or use simpler datasets',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/Facial_Emotion_Recognition',
    image: '/projects/fer-stress-detection.png',
  },
  {
    slug: 'from-the-other-side',
    number: '05',
    title: 'From the Other Side',
    type: 'Sightings board',
    description: 'A platform for sharing ghostly encounters, with pages to read sightings, upload them, and follow a live news feed.',
    tags: ['Node.js', 'JavaScript','REST', 'JSON'],
    color: 'coral',
    role: 'Full-stack developer',
    goal: 'Give paranormal sightings one place to be recorded and read.',
    learned: 'Placeholder',
    next: 'Placeholder',
    demo: 'Placeholder',
    source: 'https://github.com/dunkindonut123/fullstack-node-app',
    image: '/projects/from-the-other-side.jpg',
  },
  {
    slug: 'gold-digger',
    number: '06',
    title: 'GoldDigger',
    type: 'Gold investment app · 2026',
    description: 'A small app that shows a live gold price and records a mock investment.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Node.js'],
    color: 'coral',
    role: 'Full stack developer',
    goal: 'Let someone watch a changing gold price and log how much they would invest.',
    learned: 'A live price is a stream, not a one-time fetch. Server-Sent Events push a new price every few seconds, and the invest form has to read that same displayed price so the ounces sold match what the user saw.',
    next: 'I would open the summary dialog after a successful save, reject empty or invalid amounts, and replace the random price with a real gold-price source.',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/gold-digger',
    image: '/projects/gold-digger.jpg',
  },
  {
    slug: 'horizons-api',
    number: '07',
    title: 'Horizons API',
    type: 'Node.js REST API · 2026',
    description: 'A small HTTP API over a dataset of 19 unusual places. Clients can list them all, or filter by continent, country, and whether a site is open to the public.',
    tags: ['Node.js', 'JavaScript', 'REST'],
    color: 'coral',
    role: 'Backend developer',
    goal: 'Let a client look up interesting destinations and narrow them by location or public access.',
    learned: 'Learned how a Node HTTP server reads a request URL, filters an in-memory dataset by path and query parameters, and sends a JSON response.',
    next: 'Placeholder: I would validate query values before parsing them and add tests for the filter helpers.',
    demo: 'Placeholder',
    source: 'https://github.com/dunkindonut123/simple-REST',
    image: '/projects/horizons-api.png',
  },
  {
    slug: 'learning-journal',
    number: '08',
    title: 'Learning Journal',
    type: 'Journal site · 2026',
    description: 'A two-page journal with a hero, a responsive post grid, and an about page for sharing a bootcamp learning journey.',
    tags: ['HTML', 'CSS', 'Responsive layout'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Share a bootcamp learning journey in a simple site that stays readable on phone, tablet, and desktop.',
    learned: 'Static HTML was enough for a first journal, but copying the same post markup onto two pages made later edits error-prone.',
    next: 'I would keep posts in one data source and render both pages from it so titles and dates stay in sync.',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/learning-journal',
    image: '/projects/learning-journal.jpg',
  },
  {
    slug: 'color-scheme-generator',
    number: '09',
    title: 'Color Scheme Generator',
    type: 'Solo project · 2026',
    description: 'A palette tool that turns a seed color and scheme mode into five matching swatches with hex values.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Fetch API'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Practice fetching from a public API and rendering a usable color scheme from user input.',
    learned: 'API query parameters and response mapping matter more than the UI. The color picker # has to be stripped before the request, then each hex written onto both the swatch and the label.',
    next: 'I would add click-to-copy for hex values, handle failed requests.',
    demo: '',
    source: 'https://github.com/dunkindonut123/Color-Scheme-Generator',
    image: '/projects/color-scheme-generator.jpg',
  },
  {
    slug: 'deck-of-war',
    number: '10',
    title: 'Deck of War',
    type: 'Card game · 2026',
    description: 'A browser game of War that shuffles a deck, draws one card for each side, and keeps score until the cards run out.',
    tags: ['JavaScript', 'Fetch'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Play a full game of War from a shuffled deck without dealing or scoring by hand.',
    learned: 'Every draw depends on the deck id from the shuffle request. If that id is not saved, later draws hit a different deck or fail.',
    next: 'I would implement the real War with alot more rules.',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/deck_of_war',
    image: '/projects/deck-of-war.jpg',
  },
  {
    slug: 'momentum-dashboard',
    number: '11',
    title: 'Momentum Dashboard',
    type: 'New tab · async JS',
    description: 'A Chrome new-tab page with the time, local weather, a Dogecoin quote, and a nature photo.',
    tags: ['JavaScript', 'REST APIs', 'Chrome extension'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Open a new tab and see the time, local weather, and a photo without looking them up.',
    learned: 'How pulling data from multiple APIs work and to make a chrome extension out of my code.',
    next: 'I would show a message when location or weather fails, refresh the price on a timer, and let the coin be chosen instead of hardcoding Dogecoin.',
    demo: '',
    source: '',
    image: '/projects/momentum-dashboard.jpg',
  },
  {
    slug: 'jimmys-diner',
    number: '12',
    title: "Jimmy's Diner",
    type: 'Restaurant ordering app · 2026',
    description: 'A small diner menu where you add items, see a running total, and complete a mock checkout.',
    tags: ['HTML', 'CSS', 'JavaScript'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Let a customer order from a short menu and check out with a simple payment form.',
    learned: 'An order flow is DOM state plus event listeners. Adding an item has to update the cart, the running total, and the checkout form from the same data.',
    next: 'I would validate the payment form before checkout and keep the cart from accepting empty or invalid quantities.',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/restaurant_ordering_app',
    image: '/projects/jimmys-diner.jpg',
  },
]

export const featuredProjects = projects.slice(0, 3)

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug)
}
