export type Project = {
  slug: string
  number: string
  title: string
  type: string
  description: string
  tags: string[]
  color: 'coral' | 'blue' | 'yellow'
  role: string
  goal: string
  outcome: string
  learned: string
  next: string
  demo: string
  source: string
  image?: string
}

export const projects: Project[] = [
  {
    slug: 'funmandarin',
    number: '01',
    title: 'Fun Mandarin',
    type: 'Mandarin Learning Management System · 2026',
    description: 'A Mandarin learning platform where students practice by HSK level, and teachers and admins run classes, assignments, and level-ups in one place.',
    tags: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Supabase'],
    color: 'coral',
    role: 'Product designer & developer',
    goal: 'Give Fun Mandarin one system for class enrollment, chapter practice, and teacher oversight instead of tracking lessons outside the product.',
    outcome: 'Students join with a class code, work through locked chapter assignments, and teachers can review attempts while admins approve teachers and HSK promotions.',
    learned: 'How to interact with clients and leverage AI to build full-stack apps',
    next: 'Placeholder: I would add stronger empty states and make the planning flow easier to explain.',
    demo: 'https://www.funmandarin.id',
    source: 'https://github.com/dunkindonut123/final_ver_fun',
    image: '/projects/fun-mandarin.jpg',
  },
  {
    slug: 'the-beauty-tailor',
    number: '02',
    title: 'The Beauty Tailor',
    type: 'Tailor studio site · 2026',
    description: 'A site for a Jakarta bespoke tailor, from the atelier’s story and cloth mills to booking a consultation.',
    tags: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    color: 'blue',
    role: 'Project eveloper',
    goal: 'Give The Beauty Tailor one place to present the atelier, the mills, and the services, and let someone book a consultation without calling the shop first.',
    outcome: 'Visitors walk through heritage, craftsmanship, cloth mills, and services in Indonesian, then book on WhatsApp or send a consultation request that arrives by email.',
    learned: 'placeholder',
    next: 'placeholder',
    demo: 'https://thebeautytailor.id',
    source: 'https://github.com/dunkindonut123/tailor-shop',
    image: '/projects/the-beauty-tailor.jpg',
  },
  {
    slug: 'lost-and-found',
    number: '03',
    title: 'Lost & Found',
    type: 'Campus web app · 2026',
    description: 'A campus lost-and-found app for reporting found items, searching public listings, and claiming belongings through an admin review.',
    tags: ['React', 'Next.js', 'Supabase'],
    color: 'coral',
    role: 'Full-stack developer',
    goal: 'Give students one place to report found items and claim what they lost.',
    outcome: 'Placeholder outcome: a working flow from public listings and photo reports through claims, notifications, and admin approve/reject.',
    learned: 'Placeholder: row-level security and claim status checks had to block invalid claims, not just the form.',
    next: 'Placeholder: I would add a live demo and tighten the return flow after a claim is approved.',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/lost_and_found',
    image: '/projects/lost-and-found.jpg',
  },
  {
    slug: 'fer-stress-detection',
    number: '04',
    title: 'FER Stress Detection',
    type: 'Machine learning · 2026',
    description: 'A face model that reads four emotions and marks fear and sadness as stress.',
    tags: ['PyTorch', 'EfficientNet', 'Computer vision'],
    color: 'yellow',
    role: 'Machine learning developer',
    goal: 'Tell stress-related expressions (fear, sadness) apart from happiness and neutrality on a single photo.',
    outcome: 'EfficientNet-B0 reached 74% test accuracy and 73% macro F1 on 3,867 held-out images, after merging FER2013, AffectNet, and NHFI and dropping duplicate faces.',
    learned: 'Cutting the task to four emotions raised validation macro recall to 74.5%, from 69.9% on the five-class model. Extra test-time views did not help (−0.56% macro F1).',
    next: 'Clear the leftover cross-split duplicates (32 remained after dedup) and turn the notebook into a small inference script.',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/Facial_Emotion_Recognition',
    image: '/projects/fer-stress-detection.png',
  },
  {
    slug: 'horizons-api',
    number: '05',
    title: 'Horizons API',
    type: 'Node.js REST API · 2026',
    description: 'A small HTTP API over a dataset of 19 unusual places. Clients can list them all, or filter by continent, country, and whether a site is open to the public.',
    tags: ['Node.js', 'JavaScript', 'REST'],
    color: 'coral',
    role: 'Backend developer',
    goal: 'Let a client look up interesting destinations and narrow them by location or public access.',
    outcome: 'Placeholder outcome.',
    learned: 'Learned how a Node HTTP server reads a request URL, filters an in-memory dataset by path and query parameters, and sends a JSON response.',
    next: 'Placeholder: I would validate query values before parsing them and add tests for the filter helpers.',
    demo: 'Placeholder',
    source: 'https://github.com/dunkindonut123/simple-REST',
    image: '/projects/horizons-api.png',
  },
  {
    slug: 'learning-journal',
    number: '06',
    title: 'Learning Journal',
    type: 'Journal site · 2026',
    description: 'A two-page journal with a hero, a responsive post grid, and an about page for sharing a bootcamp learning journey.',
    tags: ['HTML', 'CSS', 'Responsive layout'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Share a bootcamp learning journey in a simple site that stays readable on phone, tablet, and desktop.',
    outcome: 'Placeholder outcome: no published result yet. The site shows a dated hero plus six posts on the home page and three recent posts on the about page.',
    learned: 'Static HTML was enough for a first version, but repeating the same post markup on both pages made later updates harder.',
    next: 'Placeholder: I would keep posts in one data source and render both pages from it so titles and dates stay in sync.',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/learning-journal',
    image: '/projects/learning-journal.jpg',
  },
  {
    slug: 'color-scheme-generator',
    number: '07',
    title: 'Color Scheme Generator',
    type: 'Solo project · 2026',
    description: 'A palette tool that turns a seed color and scheme mode into five matching swatches with hex values.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Fetch API'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Practice fetching from a public API and rendering a usable color scheme from user input.',
    outcome: 'Users can pick a color, choose a mode like analogic or triad, and see five swatches plus hex codes from The Color API.',
    learned: 'Query parameters and response mapping matter more than the UI: strip the # from the color picker, then write each hex onto both the swatch and the label.',
    next: 'I would add click-to-copy for hex values, handle failed requests, and generate the five columns from the API array instead of hardcoding them.',
    demo: '',
    source: 'https://github.com/dunkindonut123/Color-Scheme-Generator',
    image: '/projects/color-scheme-generator.jpg',
  },
  {
    slug: 'deck-of-war',
    number: '08',
    title: 'Deck of War',
    type: 'Card game · 2026',
    description: 'A browser game of War that shuffles a deck, draws one card for each side, and keeps score until the cards run out.',
    tags: ['JavaScript', 'Fetch'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Play a full game of War from a shuffled deck without dealing or scoring by hand.',
    outcome: 'New Deck shuffles via the Deck of Cards API, each draw shows both cards and updates the score, and the game names a winner when the deck is empty.',
    learned: 'The shuffle request has to save the deck id, because every later draw is a separate request that depends on it.',
    next: 'Play out a tie by drawing extra cards, and reset both scores when a new deck is shuffled.',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/deck_of_war',
    image: '/projects/deck-of-war.jpg',
  },
  {
    slug: 'momentum-dashboard',
    number: '09',
    title: 'Momentum Dashboard',
    type: 'New tab · async JS',
    description: 'A Chrome new-tab page with the time, local weather, a Dogecoin quote, and a nature photo.',
    tags: ['JavaScript', 'REST APIs', 'Chrome extension'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Open a new tab and see the time, local weather, and a photo without looking them up.',
    outcome: 'The new-tab page loads a random nature photo from Unsplash, Dogecoin’s price and 24-hour range from CoinGecko, and local weather from OpenWeatherMap after the browser shares its location. The clock updates every second.',
    learned: 'The photo, price, and weather requests had to fail on their own. A bad photo response falls back to a saved image and credit, and a bad price or weather response is logged so the clock still runs.',
    next: 'I would show a message when location or weather fails, refresh the price on a timer, and let the coin be chosen instead of hardcoding Dogecoin.',
    demo: '',
    source: '',
    image: '/projects/momentum-dashboard.jpg',
  },
  {
    slug: 'jimmys-diner',
    number: '10',
    title: "Jimmy's Diner",
    type: 'Restaurant ordering app · 2026',
    description: 'A small diner menu where you add items, see a running total, and complete a mock checkout.',
    tags: ['HTML', 'CSS', 'JavaScript'],
    color: 'coral',
    role: 'Frontend developer',
    goal: 'Let a customer order from a short menu and check out with a simple payment form.',
    outcome: 'Placeholder outcome: made personal expenses easier to review week by week.',
    learned: 'Learned the flow between JavaScript, HTML, CSS by accessing the DOM and using addEventListeners',
    next: 'Placeholder: I would add monthly summaries and better input validation.',
    demo: 'https://example.com',
    source: 'https://github.com/dunkindonut123/restaurant_ordering_app',
    image: '/projects/jimmys-diner.jpg',
  },
  // {
  //   slug: 'open-desk',
  //   number: '10',
  //   title: 'Open Desk',
  //   type: 'Job board · 2023',
  //   description: 'A local internship board that collects openings in one place instead of ten tabs.',
  //   tags: ['React', 'Node.js', 'PostgreSQL'],
  //   color: 'coral',
  //   role: 'Full-stack developer',
  //   goal: 'Shorten the search for relevant internship listings.',
  //   outcome: 'Placeholder outcome: shortened the search for relevant internship listings.',
  //   learned: 'Placeholder: filters only helped once the listing data was consistent.',
  //   next: 'Placeholder: I would add saved searches and a cleaner application tracker.',
  //   demo: 'https://example.com',
  //   source: 'https://github.com/dunkindonut123',
  // },
]

export const featuredProjects = projects.slice(0, 3)

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug)
}
